# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import grpc_server_pb2 as grpc__server__pb2


class ServerMethodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetList = channel.unary_stream(
                '/grpc_server.ServerMethods/GetList',
                request_serializer=grpc__server__pb2.BucketName.SerializeToString,
                response_deserializer=grpc__server__pb2.ListResponse.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/grpc_server.ServerMethods/GetFile',
                request_serializer=grpc__server__pb2.FileName.SerializeToString,
                response_deserializer=grpc__server__pb2.File.FromString,
                )
        self.AddFile = channel.unary_unary(
                '/grpc_server.ServerMethods/AddFile',
                request_serializer=grpc__server__pb2.FileRequest.SerializeToString,
                response_deserializer=grpc__server__pb2.Status.FromString,
                )
        self.EditFile = channel.unary_unary(
                '/grpc_server.ServerMethods/EditFile',
                request_serializer=grpc__server__pb2.FileRequest.SerializeToString,
                response_deserializer=grpc__server__pb2.Status.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/grpc_server.ServerMethods/DeleteFile',
                request_serializer=grpc__server__pb2.FileName.SerializeToString,
                response_deserializer=grpc__server__pb2.Status.FromString,
                )


class ServerMethodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerMethodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetList,
                    request_deserializer=grpc__server__pb2.BucketName.FromString,
                    response_serializer=grpc__server__pb2.ListResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=grpc__server__pb2.FileName.FromString,
                    response_serializer=grpc__server__pb2.File.SerializeToString,
            ),
            'AddFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFile,
                    request_deserializer=grpc__server__pb2.FileRequest.FromString,
                    response_serializer=grpc__server__pb2.Status.SerializeToString,
            ),
            'EditFile': grpc.unary_unary_rpc_method_handler(
                    servicer.EditFile,
                    request_deserializer=grpc__server__pb2.FileRequest.FromString,
                    response_serializer=grpc__server__pb2.Status.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=grpc__server__pb2.FileName.FromString,
                    response_serializer=grpc__server__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_server.ServerMethods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerMethods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc_server.ServerMethods/GetList',
            grpc__server__pb2.BucketName.SerializeToString,
            grpc__server__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_server.ServerMethods/GetFile',
            grpc__server__pb2.FileName.SerializeToString,
            grpc__server__pb2.File.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_server.ServerMethods/AddFile',
            grpc__server__pb2.FileRequest.SerializeToString,
            grpc__server__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_server.ServerMethods/EditFile',
            grpc__server__pb2.FileRequest.SerializeToString,
            grpc__server__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_server.ServerMethods/DeleteFile',
            grpc__server__pb2.FileName.SerializeToString,
            grpc__server__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
