# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_server.proto\x12\x0bgrpc_server\"\x1a\n\nBucketName\x12\x0c\n\x04name\x18\x01 \x01(\t\"-\n\x08\x46ileName\x12\x12\n\nbucketName\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"V\n\x0b\x46ileRequest\x12\x12\n\nbucketName\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x13\n\x0b\x63ontentType\x18\x04 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x17\n\x04\x46ile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"\x1d\n\x0cListResponse\x12\r\n\x05title\x18\x01 \x01(\t2\xbe\x02\n\rServerMethods\x12\x41\n\x07GetList\x12\x17.grpc_server.BucketName\x1a\x19.grpc_server.ListResponse\"\x00\x30\x01\x12\x35\n\x07GetFile\x12\x15.grpc_server.FileName\x1a\x11.grpc_server.File\"\x00\x12:\n\x07\x41\x64\x64\x46ile\x12\x18.grpc_server.FileRequest\x1a\x13.grpc_server.Status\"\x00\x12;\n\x08\x45\x64itFile\x12\x18.grpc_server.FileRequest\x1a\x13.grpc_server.Status\"\x00\x12:\n\nDeleteFile\x12\x15.grpc_server.FileName\x1a\x13.grpc_server.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUCKETNAME']._serialized_start=34
  _globals['_BUCKETNAME']._serialized_end=60
  _globals['_FILENAME']._serialized_start=62
  _globals['_FILENAME']._serialized_end=107
  _globals['_FILEREQUEST']._serialized_start=109
  _globals['_FILEREQUEST']._serialized_end=195
  _globals['_STATUS']._serialized_start=197
  _globals['_STATUS']._serialized_end=221
  _globals['_FILE']._serialized_start=223
  _globals['_FILE']._serialized_end=246
  _globals['_LISTRESPONSE']._serialized_start=248
  _globals['_LISTRESPONSE']._serialized_end=277
  _globals['_SERVERMETHODS']._serialized_start=280
  _globals['_SERVERMETHODS']._serialized_end=598
# @@protoc_insertion_point(module_scope)
