# Generated by Django 4.2.6 on 2023-10-12 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url_author',
            new_name='url_permission',
        ),
        migrations.AddField(
            model_name='article',
            name='themes',
            field=models.CharField(default='Theme', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='year_of_publication',
            field=models.CharField(default='2023-10-12', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
