# Generated by Django 4.2.6 on 2023-10-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0002_rename_url_author_article_url_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='themes',
            new_name='theme',
        ),
    ]
