# Generated by Django 4.2.6 on 2023-10-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0003_rename_themes_article_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='theme',
        ),
    ]
